stages:
- test_all

variables:
  MYSQL_DATABASE: flask_project_test
  MYSQL_ROOT_PASSWORD: toor333666
  FLASK_ENV: testing
  DOCKER_HOST: tcp://dockerd:2375
  IMAGE: registry.cn-hangzhou.aliyuncs.com/shanbayapp/${CI_PROJECT_NAMESPACE}-${CI_PROJECT_NAME}

cache:
  key: ${CI_JOB_NAME}
  paths:
  - ${PIP_CACHE_DIR}

#========================================= Unit Testing ================================================
test_template:
  image: "registry.cn-hangzhou.aliyuncs.com/shanbay/pymicro-pipenv"
  stage: test_all
  before_script:
  - python -V  # Print out python version for debugging
  - pipenv install --dev --deploy

  script:
  - pipenv run flake8 tests hooks
  - pipenv run pytest  -x

test_generate_project:
  image: "registry.cn-hangzhou.aliyuncs.com/shanbay/pymicro-pipenv"
  stage: test_all
  services:
  - name: mysql:5.6
    alias: mysql
  before_script:
  - python -V  # Print out python version for debugging
  - pip install cookiecutter -i https://mirrors.aliyun.com/pypi/simple
  - cookiecutter ./ --no-input -f _is_test_env="y"
  - cd flask_project
  - pipenv run pip install pip==18.0
  - pipenv install --dev --deploy
  - pipenv run pip install -r local_requirements.txt -i https://pypi.17bdc.com/simple
  script:
  - pipenv run black .
  - pipenv run flake8 app commands tests
  - pipenv run pytest tests -x
