stages:
- test
- deploy

variables:
  MYSQL_DATABASE: {{cookiecutter.project_name}}_test
  MYSQL_ROOT_PASSWORD: {{cookiecutter.database_password}}
  PIP_CACHE_DIR: "/root/.cache/pip/"
  IMAGE: python:3.6
  FLASK_ENV: testing
before_script:
- IMAGE_TAG=${IMAGE}:${CI_COMMIT_SHA:0:8}

cache:
  key: ${CI_JOB_NAME}
  paths:
  - ${PIP_CACHE_DIR}

test:
  stage: test
  image: python:3.6.7
  services:
  - name: mysql:5.6
    alias: mysql
  - name: redis:4
    alias: redis
  before_script:
  - python -V
  script:
  - pip install -U -r requirements.txt
  - flake8 {{cookiecutter.app_name}} db jobs tests
  - pytest -s -x

deploy:
  when: manual
  stage: deploy
  #  connect to  ssh server pull from git resp and rebuild image
  # and docker-compose reload
  before_script:
  - mkdir -p ~/.ssh
  - echo "$DEPLOY_SERVER_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa
  - ssh-keyscan -H vps_ip >> ~/.ssh/known_hosts
  script:
  - ./boot.sh deploy
