version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx/
    ports:
      - 8000:80
    depends_on:
      - {{cookiecutter.project_name}}

  {{cookiecutter.project_name}}:
    depends_on:
      - db
    build: .
    image:  {{cookiecutter.project_name}}:latest
    restart: always
    environment:
      DB_HOST: db
    command:  bash -c "./boot.sh run"
  db:
    image: mysql:5.7
    volumes:
      - /data/mysql/{{cookiecutter.project_name}}/data:/var/lib/mysql
    restart: always
    environment:
    # note: this should use env_file env/mysql.env and add env to .gitignore
      MYSQL_ROOT_PASSWORD: {{cookiecutter.database_password}}
      MYSQL_DATABASE: {{cookiecutter.project_name}}
#    env_file:
#      - env/mysql.env